# permissions for end users to view personas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: persona-viewer-role
rules:
- apiGroups:
  - comp.genesis.xyz.com
  resources:
  - personas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - comp.genesis.xyz.com
  resources:
  - personas/status
  verbs:
  - get
